# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB-TOKEN: ${{secrets.PLUGIN_ACTIONS}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # flutter java 环境
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "8"
          
      # flutter 环境
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" 
          
      # 引用私有库
#       - name: get jubiter-plugin
#         uses: actions/checkout@v2
#         with:
#           repository: JubiterWallet/JuBiter-Plugin
#           ref: 2.3
#           token: ${{secrets.PLUGIN_ACTIONS}}
#           path: ./.github/actions/JuBiter-Plugin
          
#       - uses: ./.github/actions/JuBiter-Plugin

      - name: Config git
        run: |
          git config --global github.token  ${{secrets.PLUGIN_ACTIONS}} \
          git clone https://github.com/JubiterWallet/JuBiter-Plugin.git repo
 
      - run: flutter pub get
        env:
          token: ${{secrets.PLUGIN_ACTIONS}}
            
#       - run: flutter analyze
      - run: flutter build apk
        working-directory: ./
      
      # 上传 app 文件
      - name: upload artifects
        uses: actions/upload-artifact@v2
        with:
          name: jubiter-android-app
          path: build/app/outputs/flutter-apk/app-release.apk

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
