# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'
    
  pull_request:
    branches: [ main ]
#   milestone:
#     types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # 正则检测版本号
  change_tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      # 对外返回值，true: 正则匹配符合，false: 不符合
      match_value: ${{ steps.regex-match.outputs.match != '' }}
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1.0.0
        
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.tag.outputs.tag }}
          regex: '^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'
  

  # This workflow contains a single job called "build"
  build:
    needs: [change_tag]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ needs.change_tag.outputs.match_value }}
    
    #     只有tag 才运行
#     if: startsWith(github.ref, 'refs/tags/')
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Check tag version
#         if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
            echo ${{ needs.change_tag.outputs.match_value }}
      
      # flutter java 环境
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "8"
          
      # flutter 环境
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" 
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: ./release_logs/${{github.ref}}.md
          run: |
            echo "github.ref >>> ${{github.ref}}"
            echo "github.event.ref >>> ${{github.event.ref}}"
          
      # 引用私有库
#       - name: get jubiter-plugin
#         uses: actions/checkout@v2
#         with:
#           repository: JubiterWallet/JuBiter-Plugin
#           ref: 2.3
#           token: ${{secrets.PLUGIN_ACTIONS}}
#           path: ./.github/actions/JuBiter-Plugin
          
#       - uses: ./.github/actions/JuBiter-Plugin

#       - name: Config git
#         env: 
#           user: JW_WHB
#         run: |
#           git config --global github.user  ${user}
#           git config --global github.token  ${{secrets.PLUGIN_ACTIONS}}

      - name: Configure git for private modules 
        env: 
          TOKEN: ${{ secrets.PLUGIN_ACTIONS }} 
        run: git config --global url."https://${TOKEN}@github.com".insteadOf https://github.com
 
      - run: flutter pub get
            
#       - run: flutter analyze
      - run: flutter build apk --debug
#         working-directory: ./
      
      # 上传 app 文件
      - name: upload artifects
        uses: actions/upload-artifact@v2
        with:
          name: jubiter-android-app
          path: build/app/outputs/flutter-apk/app-debug.apk

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
